<?php

namespace ServiceDirect\Partners;

/**
 * Class ServiceCategories
 * Most of our available service categories
 * @see https://api.servicedirect.com/resources/service_categories?is_marketplace=1
 *  for the most updated list of available service categories
 * @package ServiceDirect\Partners
 */
abstract class ServiceCategories
{
    const AirDuctCleaning = 1;
    const AirConditioning = 2;
    const Cabinets = 3;
    const CarpetCleaning = 4;
    const Countertops = 5;
    const CustomHomes = 7;
    const Electrician = 9;
    const Flooring = 12;
    const Handyman = 13;
    const Heating = 14;
    const Landscaping = 16;
    const MaidService = 17;
    const MoldRemoval = 18;
    const Painting = 19;
    const Plumbing = 20;
    const SwimmingPools = 21;
    const Remodeling = 22;
    const Roofing = 24;
    const Siding = 25;
    const Waterproofing = 26;
    const WaterDamageRestoration = 27;
    const Windows = 29;
    const ApplianceRepair = 36;
    const KitchenRemodeling = 39;
    const Carpentry = 40;
    const Sunrooms = 41;
    const PestControl = 42;
    const FireDamageRestoration = 45;
    const Drywall = 48;
    const Movers = 51;
    const BathRemodeling = 55;
    const HomeAdditions = 59;
    const Decks = 60;
    const BasementRemodeling = 61;
    const WindowReplacement = 83;
    const HomeSecurity = 88;
    const Insulation = 90;
    const Gutters = 96;
    const FoundationRepair = 99;
    const TreeService = 100;
    const Dentist = 102;
    const GarageDoors = 106;
    const Solar = 107;
    const PersonalInjuryLawyer = 109;
    const PressureWashing = 114;
    const Masonry = 115;
    const HomeInspections = 116;
    const Fencing = 119;
    const Locksmith = 120;
    const Paving = 125;
    const JunkRemoval = 127;
    const StairLifts = 130;
    const DoorInstallation = 136;
    const AutomaticGates = 143;
    const ChimneyCleaning = 146;
    const StructuralEngineer = 150;
    const WildlifeRemoval = 159;
    const PropertyManagement = 160;
    const BankruptcyLawyer = 163;
    const BedBugRemoval = 164;
    const TileInstaller = 166;
    const DivorceAttorney = 175;
    const AccidentAttorney = 177;
    const BuildingDemolition = 178;
    const DUILawyer = 182;
    const ConcretePaving = 184;
    const RodentRemoval = 194;
    const AutoBodyShop = 195;
    const AutoGlass = 196;
    const AutoRepairAndService = 197;
    const TowingService = 198;
    const Lawncare = 200;
    const Architects = 201;
    const Asbestos = 202;
    const Asphalt = 203;
    const CarpetAndRugDealers = 204;
    const DecoratorsAndDesigners = 205;
    const DumpsterRental = 206;
    const Furniture = 207;
    const HomeAppraisals = 208;
    const HomeWarranty = 209;
    const PortableToilets = 210;
    const SatelliteTVService = 211;
    const SelfStorage = 212;
    const TVRepair = 213;
    const Welders = 214;
    const ThreeMEarplugsLawyers = 215;
    const CollectionsLawyers = 216;
    const CriminalLawyers = 217;
    const EmploymentLawyers = 218;
    const ForeclosureLawyers = 219;
    const HerniaMeshLawyers = 220;
    const ImmigrationLawyers = 221;
    const MedicalMalpracticeLawyers = 222;
    const MesotheliomaLawyers = 223;
    const ProductLiabilityLawyers = 224;
    const RoundupLawyers = 225;
    const SexualHarassmentLawyers = 226;
    const SocialSecurityDisabilityLawyers = 227;
    const TalcumPowderLawyers = 228;
    const TrafficLawyers = 229;
    const WillsAndEstatePlanningLawyers = 230;
    const WorkersCompensationLawyers = 231;
    const WrongfulDeathLawyers = 232;
    const FamilyLawyers = 233;
    const RealEstateLawyers = 234;
    const Chiropractors = 235;
    const Dermatologists = 236;
    const DrugAndAlcoholAddictionTreatment = 237;
    const Optometrists = 238;
    const PhysicalTherapists = 239;
    const Podiatrists = 240;
    const Veterinarians = 241;
    const AutoInsurance = 242;
    const HealthInsurance = 243;
    const HomeownersInsurance = 244;
    const LifeInsurance = 245;
    const PetInsurance = 246;
    const ComputerRepair = 247;
    const CopierRepair = 248;
    const FlightBooking = 249;
    const Florists = 250;
    const Hotels = 251;
    const InternetAndCable = 252;
    const BathConversions = 253;
}
